#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-json-lib
Version  : 1
Release  : 1
URL      : https://downloads.sourceforge.net/project/json-lib/json-lib/json-lib-2.3/json-lib-2.3-jdk15-sources.jar
Source0  : https://downloads.sourceforge.net/project/json-lib/json-lib/json-lib-2.3/json-lib-2.3-jdk15-sources.jar
Source1  : https://repo.gradle.org/gradle/libs-releases/net/sf/json-lib/json-lib/2.3/json-lib-2.3-jdk15.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/net/sf/json-lib/json-lib/2.3/json-lib-2.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : mvn-json-lib
Requires: mvn-json-lib-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-json-lib package.
Group: Data

%description data
data components for the mvn-json-lib package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/json-lib/json-lib/2.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/sf/json-lib/json-lib/2.3/json-lib-2.3-jdk15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/json-lib/json-lib/2.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/sf/json-lib/json-lib/2.3/json-lib-2.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/sf/json-lib/json-lib/2.3/json-lib-2.3-jdk15.jar
/usr/share/java/.m2/repository/net/sf/json-lib/json-lib/2.3/json-lib-2.3.pom
