#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-json-lib
Version  : 1
Release  : 3
URL      : https://downloads.sourceforge.net/project/json-lib/json-lib/json-lib-2.3/json-lib-2.3-jdk15-sources.jar
Source0  : https://downloads.sourceforge.net/project/json-lib/json-lib/json-lib-2.3/json-lib-2.3-jdk15-sources.jar
Source1  : https://repo.gradle.org/gradle/libs-releases/net/sf/json-lib/json-lib/2.3/json-lib-2.3-jdk15.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/net/sf/json-lib/json-lib/2.3/json-lib-2.3.pom
Source3  : https://repo.gradle.org/gradle/libs-releases/net/sf/json-lib/json-lib/2.4/json-lib-2.4-jdk15.jar
Source4  : https://repo.gradle.org/gradle/libs-releases/net/sf/json-lib/json-lib/2.4/json-lib-2.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
No detailed description available

%prep
%setup -q -n META-INF

%build

%install

%files
%defattr(-,root,root,-)
